### ISSUE TITLE
Can not install moderna theme

### ISSUE THREAD

**Issue by sinjorjob** [hirokiky/mezzaninetheme-moderna#1]
I can not install moderna theme.
When start  [pip install mezzaninetheme-moderna], the following error occures.
-------------------------------------------------------------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\xxxxx\AppData\Local\Temp\pip-build-k_zyfhi7\mezzaninetheme-moderna\

My environment is 

Mezzanine 4.2.3
Django 1.10.8
Python 3.6.3
SQLite 3.14.2
Windows 10

※the installation of  Mezzanine is done no error, and  can access to default index pages.
※can not change theme from default to modern one.

What is the cause of this issue?

**Comment by zmomen** [comment]
I couldn't install it either. I am getting this error.
```
$ pip install mezzaninetheme-moderna
Collecting mezzaninetheme-moderna
  Using cached mezzaninetheme-moderna-1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/8c/h5s1l4sj4092w8vt1ndwhcbr0000gn/T/pip-build-edulpj8i/mezzaninetheme-moderna/setup.py", line 5, in <module>
        README = open(os.path.join(here, 'README.md')).read()
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/8c/h5s1l4sj4092w8vt1ndwhcbr0000gn/T/pip-build-edulpj8i/mezzaninetheme-moderna/README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/8c/h5s1l4sj4092w8vt1ndwhcbr0000gn/T/pip-build-edulpj8i/mezzaninetheme-moderna/
```
